spring.application.name=gestao_empresarial
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/empresadb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:empresa_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:empresa_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

admin.username=admin
admin.password=admin123

jwt.secret=sua_chave_secreta_com_pelo_menos_32_caracteres_aqui
jwt.expiration-ms=3600000

